---

- set_fact:
    os_security_group_name: '{{ os_project_name }}-icmp'
- import_tasks: security_group.yml
- block:
    - import_tasks: security_group_rule.yml
    - os_security_group_rule:
        security_group: '{{ os_security_group_name }}'
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: -1
        port_range_max: -1
        direction: ingress
        protocol: icmp
        validate_certs: '{{ os_validate_certs }}'
  when: os_project_state == 'present' and os_security_group_modify.changed
