---

- set_fact:
    os_security_group_name: '{{ os_project_name }}-ipa'
- import_tasks: security_group.yml
- block:
    - import_tasks: security_group_rule.yml
    - os_security_group_rule:
        security_group: '{{ os_security_group_name }}'
        remote_group: '{{ os_security_group_name }}'
        port_range_min: '{{ item.port }}'
        port_range_max: '{{ item.port }}'
        direction: ingress
        protocol: '{{ item.protocol }}'
        validate_certs:
      with_items:
        - { port: 80, protocol: tcp    }
        - { port: 443, protocol: tcp   }
        - { port: 389, protocol: tcp   }
        - { port: 636, protocol: tcp   }
        - { port: 88, protocol: tcp    }
        - { port: 88, protocol: udp    }
        - { port: 464, protocol: tcp   }
        - { port: 464, protocol: udp   }
        - { port: 7389, protocol: tcp  }
  when: os_project_state == 'present' and os_security_group_modify.changed
