---

- set_fact:
   os_security_group_name: '{{ os_project_name }}-netdata'
- import_tasks: security_group.yml
- block:
   - import_tasks: security_group_rule.yml
   - os_security_group_rule:
       security_group: '{{ os_security_group_name }}'
       remote_ip_prefix: '{{ prometheus_ip }}'
       port_range_min: 19999
       port_range_max: 19999
       direction: ingress
       protocol: tcp
       validate_certs: '{{ os_validate_certs }}'
 when: os_project_state == 'present' and os_security_group_modify.changed
