---

- set_fact:
    os_security_group_name: '{{ os_project_name }}-puma'
- import_tasks: security_group.yml
- block:
    - import_tasks: security_group_rule.yml
    - os_security_group_rule:
        security_group: '{{ os_security_group_name }}'
        remote_ip_prefix: '{{ os_subnet_cidr }}'
        port_range_min: 3000
        port_range_max: 3000
        protocol: tcp
        validate_certs: '{{ os_validate_certs }}'
        direction: ingress
  when: os_project_state == 'present' and os_security_group_modify.changed
