---

- set_fact:
    os_security_group_name: '{{ os_project_name }}-zookeeper'
- import_tasks: security_group.yml
- block:
    - import_tasks: security_group_rule.yml
    - os_security_group_rule:
        security_group: '{{ os_security_group_name }}'
        remote_ip_prefix: '{{ os_subnet_cidr }}'
        port_range_min: 2181
        port_range_max: 2181
        direction: ingress
        protocol: tcp
        validate_certs: '{{ os_validate_certs }}'
    - os_security_group_rule:
        security_group: "{{ os_security_group_name }}"
        port_range_min: '{{ item }}'
        port_range_max: '{{ item }}'
        remote_group: "{{ os_security_group_name }}"
        direction: ingress
        protocol: tcp
        validate_certs: '{{ os_validate_certs }}'
      with_items:
        - 3888
        - 2888
  when: os_project_state == 'present' and os_security_group_modify.changed
