---
# tasks file for os_mgmt

- block:

    - block:
        - name: set os_username
          set_fact:
            os_username: '{{ ansible_env.OS_USERNAME }}'
      rescue:
        - pause:
            prompt: Please enter you OpenStack user name
            echo: yes
          register: result
      - name: set os_username
        set_fact:
          os_username: '{{ result.user_input }}'

    - block:
        - name: set os_password
          set_fact:
            os_password: '{{ ansible_env.OS_PASSWORD }}'
      rescue:
        - pause:
            prompt: Please enter your OpenStack Password
            echo: no
          register: result
      - name: set os_password
        set_fact:
          os_password: '{{ result.user_input }}'

    - block:
        - name: set os_project_name
          set_fact:
            os_project_name: '{{ ansible_env.OS_PROJECT_NAME }}'
          when: os_project_name is not defined or os_project_name == ''
      rescue:
        - name: set os_project_name
          set_fact:
            os_project_name: '{{ os_project_name_default }}'
          when: os_project_name_default is defined or os_project_name_default != ''
      - blocK:
          - pause:
              prompt: Please enter your OpenStack Project Name
              echo: yes
            register: result
          - name: set os_project_name
            set_fact:
              os_project_name: '{{ result.user_input }}'
        when: os_project_name_default is not defined or os_project_name_default == ''

    - block:
        - name: set os_project_id
          set_fact:
            os_project_id: '{{ ansible_env.OS_PROJECT_ID }}'
      rescue:
        - name: set os_project_id
          set_fact:
            os_project_id: '{{ os_project_id_default }}'

    - block:
        - name: set os_user_domain_name
          set_fact:
            os_user_domain_name: '{{ ansible_env.OS_USER_DOMAIN_NAME }}'
      rescue:
        - name: set os_user_domain_name
          set_fact:
            os_user_domain_name: '{{ os_user_domain_name_default }}'

    - block:
        - name: set os_auth_url
          set_fact:
            os_auth_url: '{{ ansible_env.OS_AUTH_URL }}'
      rescue:
        - name: set os_auth_url
          set_fact:
            os_auth_url: '{{ os_auth_url_default }}'

    - block:
        - name: set os_identity_api_version
          set_fact:
            os_identity_api_version: '{{ ansible_env.OS_IDENTITY_API_VERSION }}'
      rescue:
        - name: set os_identity_api_version
          set_fact:
            os_identity_api_version: '{{ os_identity_api_version_default }}'

    - block:
        - name: set os_project_domain_id
          set_fact:
            os_project_domain_id: '{{ ansible_env.OS_PROJECT_DOMAIN_ID }}'
      rescue:
        - name: set os_project_domain_id
          set_fact:
            os_project_domain_id: '{{ os_project_domain_id_default }}'

    - block:
        - name: set os_region_name
          set_fact:
            os_region_name: '{{ ansible_env.OS_REGION_NAME }}'
      rescue:
        - name: set os_region_name
          set_fact:
            os_region_name: '{{ os_region_name_default }}'

    - block:
        - name: set os_interface
          set_fact:
            os_interface: '{{ ansible_env.OS_INTERFACE }}'
      rescue:
        - name: set os_interface
          set_fact:
            os_interface: '{{ os_interface_default }}'

  tags: always


- import_tasks: os_tasks_present.yml
  environment:
    OS_USERNAME: '{{ os_username }}'
    OS_PASSWORD: '{{ os_password }}'
    OS_PROJECT_NAME: '{{ os_project_name }}'
    OS_PROJECT_ID: '{{ os_project_id }}'
    OS_USER_DOMAIN_NAME: '{{ os_user_domain_name }}'
    OS_AUTH_URL: '{{ os_auth_url }}'
    OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
    OS_PROJECT_DOMAIN_ID: '{{ os_project_domain_id }}'
    OS_REGION_NAME: '{{ os_region_name }}'
    OS_INTERFACE: '{{ os_interface }}'
  when: os_project_state == 'present'


- block:

  - name: '{{ os_project_state }} {{ os_project_name }}'
    pause:
      prompt: Please enter OpenStack Project Name ({{ os_project_name }}) to DELETE it
      echo: yes
    register: result

  - meta: end_play
    when: os_project_name != result.user_input

  - import_tasks: os_tasks_absent.yml
    environment:
      OS_USERNAME: '{{ os_username }}'
      OS_PASSWORD: '{{ os_password }}'
      OS_PROJECT_NAME: '{{ os_project_name }}'
      OS_PROJECT_ID: '{{ os_project_id }}'
      OS_USER_DOMAIN_NAME: '{{ os_user_domain_name }}'
      OS_AUTH_URL: '{{ os_auth_url }}'
      OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
      OS_PROJECT_DOMAIN_ID: '{{ os_project_domain_id }}'
      OS_REGION_NAME: '{{ os_region_name }}'
      OS_INTERFACE: '{{ os_interface }}'
    when: os_project_name == result.user_input

  when: os_project_state == 'absent'
