---
# tasks file for os_mgmt

- import_tasks: asserts.yml
  tags: always

- import_tasks: present.yml
  environment:
    OS_USERNAME: '{{ os_username }}'
    OS_PASSWORD: '{{ os_password }}'
    OS_PROJECT_NAME: '{{ os_project_name }}'
    OS_PROJECT_ID: '{{ os_project_id }}'
    OS_USER_DOMAIN_NAME: '{{ os_user_domain_name }}'
    OS_AUTH_URL: '{{ os_auth_url }}'
    OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
    OS_PROJECT_DOMAIN_ID: '{{ os_project_domain_id }}'
    OS_REGION_NAME: '{{ os_region_name }}'
    OS_INTERFACE: '{{ os_interface }}'
  when: os_project_state == 'present'


- block:

  - name: '{{ os_project_state }} {{ os_project_name }}'
    pause:
      prompt: Please enter OpenStack Project Name ({{ os_project_name }}) to DELETE it
      echo: yes
    register: result

  - meta: end_play
    when: os_project_name != result.user_input

  - import_tasks: absent.yml
    environment:
      OS_USERNAME: '{{ os_username }}'
      OS_PASSWORD: '{{ os_password }}'
      OS_PROJECT_NAME: '{{ os_project_name }}'
      OS_PROJECT_ID: '{{ os_project_id }}'
      OS_USER_DOMAIN_NAME: '{{ os_user_domain_name }}'
      OS_AUTH_URL: '{{ os_auth_url }}'
      OS_IDENTITY_API_VERSION: '{{ os_identity_api_version }}'
      OS_PROJECT_DOMAIN_ID: '{{ os_project_domain_id }}'
      OS_REGION_NAME: '{{ os_region_name }}'
      OS_INTERFACE: '{{ os_interface }}'
    when: os_project_name == result.user_input

  when: os_project_state == 'absent'
