---

- name: remove default rulles
  os_security_group_rule:
    security_group: '{{ os_security_group_name }}'
    ethertype: '{{ ethertype }}'
    validate_certs: '{{ os_validate_certs }}'
    direction: egress
    state: absent
  with_items:
    - IPv6
    - IPv4
  loop_control:
    loop_var: ethertype
